### ISSUE TITLE
problem registering

### ISSUE THREAD

**Issue by ghost** [nisabmohd/ChatGPT#13]
i am getting this 
![image](https://user-images.githubusercontent.com/119863571/220959090-79c22a10-b914-438b-9419-041fb8e7e72e.png)

if i want to register

**Comment by ghost** [comment]
Hello

**Comment by nisabmohd** [comment]
Yeah ill sure work on it. I was quite busy at workplace

**Comment by ghost** [comment]
oke

**Comment by BigBangBit** [comment]
I hope it can help you
(console debug message)

POST   http://localhost:5173/undefined/auth/login

**Comment by ghost** [comment]
i am getting a gray screen

**Comment by nisabmohd** [comment]
It would be great if you post the screenshot of network call from browser also console messages..

**Comment by ghost** [comment]
Bruh

I am only getting that "X" Nothing in consols

**Comment by ghost** [comment]
![Screenshot_20230429_092016_VNC Viewer](https://user-images.githubusercontent.com/119863571/235289566-9de16d3c-5aee-412d-9ca8-2136d9d72382.jpg)
![Screenshot_20230429_085409_VNC Viewer](https://user-images.githubusercontent.com/119863571/235289568-c3f99475-6fc8-4351-80e3-a48c393fb1b2.jpg)
![Screenshot_20230429_085316_VNC Viewer](https://user-images.githubusercontent.com/119863571/235289570-1a663900-a5b7-4e70-af5d-dc3dac44c0f7.jpg)

**Comment by edoloughlin** [comment]
Any update on this? I'm seeing the same issue. My network tab shows a

```
POST http://<my ip>:3001/undefined/auth/signup
```

This is read from [client/src/url.ts](https://github.com/nisabmohd/ChatGPT/blob/85a17051f584bb96bc799e39b49c71338fd8ca5c/client/src/url.ts#L1), which should be set by `client/.env`. I created this per the instructions, containing:

```shell
VITE_API_URL=http://localhost:8000
```

But the [handleSignup fn](https://github.com/nisabmohd/ChatGPT/blob/85a17051f584bb96bc799e39b49c71338fd8ca5c/client/src/pages/Signup.tsx#L17) isn't calling localhost8000.

I've also changed my `vite.config.ts` to listen on all interfaces:

```javascript
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    host: '0.0.0.0', // Listen on all network interfaces
    port: 3000, // Specify the desired port number
  }
});
```

**Comment by ghost** [comment]
😂
