### ISSUE TITLE
update UI/features

### ISSUE THREAD

**Issue by jordon31** [nisabmohd/ChatGPT#16]
I don't know if you will read this post.. 

 1) add a history system
 2) add live typing
 3) improve the UI to be the same as on GPT chat
 4) Add a login system with Google+Microsoft (if it's not too complicated for you)
 5) An email verification for registration.
 make sure everything is compatible via mobile
 
 ------------
 
 6) Enter a selection of models as in GPT Plus. (gpt 3.5 turbo and gpt4 API)
 
 
![image](https://user-images.githubusercontent.com/94505651/235466159-2902e97b-6beb-4b0e-9365-2fbe538b4e43.png)

button : https://sharetext.me/neq5eadsbh
ico gpt4:  https://sharetext.me/0qi63aotv2

-------
I suggest you also include the rules so that I can customize it myself to train it well. "https://platform.openai.com/docs/guides/chat"

**Comment by onetwothreesudo** [comment]
It's really hard doing this. This project is complicated enough. Give them a break dude

**Comment by jordon31** [comment]
> It's really hard doing this. This project is complicated enough. Give them a break dude

 Openai added a lot of things. plugins and more.. useless this project

**Comment by nisabmohd** [comment]
> > It's really hard doing this. This project is complicated enough. Give them a break dude
> 
>  Openai added a lot of things. plugins and more.. useless this project 

Thank you for your suggestion. If you see already typing effect, chat history.. added.
 And I'll be adding google auth soon. But i don't consider you opinion on my project.

If you really build this from scratch you'll understand. You can refer openai docs too.
Me as a developer won't pay openai for all features and models. 

Learn to appreciate.

**Comment by onetwothreesudo** [comment]
> > It's really hard doing this. This project is complicated enough. Give them a break dude
> 
> Openai added a lot of things. plugins and more.. useless this project

Bro OpenAI is a large organization with lots of developers

**Comment by onetwothreesudo** [comment]
> > It's really hard doing this. This project is complicated enough. Give them a break dude
> 
> Openai added a lot of things. plugins and more.. useless this project

Put yourself in his shoes

**Comment by jordon31** [comment]
https://github.com/danny-avila/LibreChat

 view this
