### ISSUE TITLE
 Invalid `prisma.user.findUnique()` invocation:   error: Environment variable not found: DATABASE_URL.   -->  schema.prisma:7    |   6 |   provider = "mongodb"  7 |   url      = env("DATABASE_URL")    |   Validation Error Count: 1

### ISSUE THREAD

**Issue by zdwork** [nisabmohd/ChatGPT#19]
Invalid `prisma.user.findUnique()` invocation:

error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   | 
 6 |   provider = "mongodb"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1

**Comment by nisabmohd** [comment]
Please add .env file in project where add the database connection url for MongoDB
