### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by hunchojohn** [nisabmohd/ChatGPT#2]
Content only displays in the mid screen, instead of the whole screen on mobile phones 8

**Comment by nisabmohd** [comment]
Fixed mobile responsiveness

**Comment by nisabmohd** [comment]
![Screenshot_20230109_101121](https://user-images.githubusercontent.com/76525761/211242303-7326198e-e53c-4d64-8659-59b06059ff92.jpg)
