### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by revbin** [nisabmohd/ChatGPT#3]
Hi

can you please add to README a detailed  install process please .

regards

**Comment by nisabmohd** [comment]
Yup done  👍
https://github.com/nisabmohd/ChatGPT/blob/master/README.md

**Comment by drygoatair** [comment]
Actually, you should add `npm i` or else it won't run if you don't have the required dependencies installed.

**Comment by nisabmohd** [comment]
> Actually, you should add `npm i` or else it won't run if you don't have the required dependencies installed.

Sure gonna update with my latest version of project
