### ISSUE TITLE
Quick question, why do you need nodejs and a database?

### ISSUE THREAD

**Issue by ncesar** [nisabmohd/ChatGPT#5]
Couldn't you just use the frontend to fetch api calls to OpenAI?

Are you using database and node just to have user login/signup or is there something else I didnt saw on the code?

Thanks and good job!

**Comment by nisabmohd** [comment]
The OpenAi docs recommend to use it with Node for security reasons. And I have uses api key authentication in Node beacuse you have to be authorised inorder to make request.

**Comment by ncesar** [comment]
makes totally sense, thank you and nice job here!
